# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvival',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('imei', models.CharField(db_column='Imei', max_length=50)),
                ('firsttime', models.DateTimeField(blank=True, db_column='FirstTime', null=True)),
                ('lasttime', models.DateTimeField(blank=True, db_column='LastTime', null=True)),
            ],
            options={
                'db_table': 'UserSurvival',
            },
        ),
    ]
