# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_usersurvival'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='action', max_length=50)),
                ('time', models.DateTimeField(blank=True, db_column='time', null=True)),
            ],
            options={
                'db_table': 'AnalyzeRecord',
            },
        ),
    ]
